# Automations avancées pour KNX avec format Time (DPT 10.001)
# 
# Cette version utilise le format Time de KNX (DPT 10.001) qui est plus standard
# Format: HH:MM:SS (3 bytes)
#
# Configuration requise :
# 1. Installer l'intégration KNX dans Home Assistant
# 2. Configurer vos adresses GA (Group Address) dans knx.yaml
# 3. Adapter les adresses GA ci-dessous selon votre configuration

automation:
  # Envoi de l'heure d'Alfajr au format Time
  - alias: "KNX - Envoyer heure Alfajr (Time)"
    id: knx_send_alfajr_time
    trigger:
      - platform: state
        entity_id: sensor.salat_alfajr
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_alfajr') != 'unknown' and states('sensor.salat_alfajr') != 'unavailable' }}"
    action:
      - service: knx.send
        data:
          address: "1/1/1"  # Adresse GA à adapter
          payload: "{{ states('sensor.salat_alfajr') }}:00"  # Ajoute les secondes
          type: "DPTTime"  # Format Time KNX (DPT 10.001)

  # Envoi de l'heure de Chourouq au format Time
  - alias: "KNX - Envoyer heure Chourouq (Time)"
    id: knx_send_chourouq_time
    trigger:
      - platform: state
        entity_id: sensor.salat_chourouq
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_chourouq') != 'unknown' and states('sensor.salat_chourouq') != 'unavailable' }}"
    action:
      - service: knx.send
        data:
          address: "1/1/2"
          payload: "{{ states('sensor.salat_chourouq') }}:00"
          type: "DPTTime"

  # Envoi de l'heure de Dhuhr au format Time
  - alias: "KNX - Envoyer heure Dhuhr (Time)"
    id: knx_send_dhuhr_time
    trigger:
      - platform: state
        entity_id: sensor.salat_dhuhr
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_dhuhr') != 'unknown' and states('sensor.salat_dhuhr') != 'unavailable' }}"
    action:
      - service: knx.send
        data:
          address: "1/1/3"
          payload: "{{ states('sensor.salat_dhuhr') }}:00"
          type: "DPTTime"

  # Envoi de l'heure d'Asr au format Time
  - alias: "KNX - Envoyer heure Asr (Time)"
    id: knx_send_asr_time
    trigger:
      - platform: state
        entity_id: sensor.salat_asr
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_asr') != 'unknown' and states('sensor.salat_asr') != 'unavailable' }}"
    action:
      - service: knx.send
        data:
          address: "1/1/4"
          payload: "{{ states('sensor.salat_asr') }}:00"
          type: "DPTTime"

  # Envoi de l'heure de Maghrib au format Time
  - alias: "KNX - Envoyer heure Maghrib (Time)"
    id: knx_send_maghrib_time
    trigger:
      - platform: state
        entity_id: sensor.salat_maghrib
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_maghrib') != 'unknown' and states('sensor.salat_maghrib') != 'unavailable' }}"
    action:
      - service: knx.send
        data:
          address: "1/1/5"
          payload: "{{ states('sensor.salat_maghrib') }}:00"
          type: "DPTTime"

  # Envoi de l'heure d'Ishae au format Time
  - alias: "KNX - Envoyer heure Ishae (Time)"
    id: knx_send_ishae_time
    trigger:
      - platform: state
        entity_id: sensor.salat_ishae
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_ishae') != 'unknown' and states('sensor.salat_ishae') != 'unavailable' }}"
    action:
      - service: knx.send
        data:
          address: "1/1/6"
          payload: "{{ states('sensor.salat_ishae') }}:00"
          type: "DPTTime"

  # Envoi de la prochaine prière (code numérique)
  - alias: "KNX - Envoyer prochaine prière"
    id: knx_send_next_prayer_code
    trigger:
      - platform: state
        entity_id: sensor.salat_next_prayer
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_next_prayer') != 'unknown' and states('sensor.salat_next_prayer') != 'unavailable' }}"
    action:
      - service: knx.send
        data:
          address: "1/1/7"
          payload: >
            {% set prayer = states('sensor.salat_next_prayer') | lower %}
            {% if prayer == 'alfajr' %}1
            {% elif prayer == 'chourouq' %}2
            {% elif prayer == 'dhuhr' %}3
            {% elif prayer == 'asr' %}4
            {% elif prayer == 'maghrib' %}5
            {% elif prayer == 'ishae' %}6
            {% else %}0{% endif %}
          type: "DPTValue1Ucount"

  # Envoi initial au démarrage
  - alias: "KNX - Envoyer toutes les heures au démarrage"
    id: knx_send_all_on_startup_time
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: template
        value_template: "{{ states('sensor.salat_alfajr') != 'unknown' }}"
    action:
      - delay: "00:00:05"  # Attendre 5 secondes après le démarrage
      - service: automation.trigger
        data:
          entity_id:
            - automation.knx_send_alfajr_time
            - automation.knx_send_chourouq_time
            - automation.knx_send_dhuhr_time
            - automation.knx_send_asr_time
            - automation.knx_send_maghrib_time
            - automation.knx_send_ishae_time
            - automation.knx_send_next_prayer_code

